[package]
name = "test-lib"
version = "0.1.0"
edition = "2021"

[features]
default = []
"native-serial" = ["dep:serialport"]

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "1"
tracing = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
parking_lot = "0.12"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
uuid = { version = "1", features = ["v4"] }
serialport = { version = "4", optional = true }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3"

[lib]
path = "../src-tauri/src/lib.rs"
